[package]
name = "windows_vulkan_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
universalui_win32 = { path = "../universalui_win32" }